---
- name: Playbook to add MediaVM mounts
  become: true
  hosts: localhost
  connection: local
  vars:
    mount_src: /dev/sdb
    mount_path: /data
  tasks:
    - name: Install autofs
      ansible.builtin.apt:
        name: autofs
        state: latest
      become: true
    - name: Setup auto.nfs file
      ansible.builtin.copy:
        src: ~/homeserver/conf/autofs/auto.nfs
        dest: /etc/auto.nfs
        backup: true
    - name: Create List of mounted drives
      set_fact:
        mounted_devices: "{{ ansible_mounts|json_query('[].device') }}"
    - name: Create file system
      filesystem:
        fstype: ext4
        dev: "{{ mount_src }}"
      when: mount_src not in mounted_devices
    - name: Mount file system
      mount:
        path: "{{ mount_path }}"
        src: "{{ mount_src }}"
        fstype: ext4
        state: mounted
      when: mount_src not in mounted_devices