---
- name: Playbook to download private secrets from github
  hosts: localhost
  connection: local
  vars:
    username: leinad13
    reponame: homeserversecrets
    dest: ~/homeserversecrets
    main: ~/homeserver
    user: dan
    group : dan
  tasks:
    - name: Clone Private Git Repo
      ansible.builtin.git:
        repo: "https://{{ token }}@github.com/{{ username }}/{{ reponame }}.git"
        dest: "{{ dest }}"
    - name: Copy .env File to Docker Compose Project Folder
      ansible.builtin.copy:
        src: "{{ dest }}/mediastack/.env"
        dest: "{{ main }}/docker/mediastack"
        backup: true
    - name: Get env file content # https://stackoverflow.com/questions/60209185/ansible-environment-variables-from-env-file
      ansible.builtin.slurp:
        src: "{{ main }}/docker/mediastack/.env"
      register: env_file_content
    - name: Parse Environment
      ansible.builtin.set_fact:
        env_vars: "{{ (env_file_content.content | b64decode).split('\n') | map('regex_replace', '^#.*', '') | select | map('regex_replace', '([^=]*)=(.*)', '\\1: \\2') | join('\n') | from_yaml }}"
    - name: Display Vars
      ansible.builtin.debug:
        msg: Testing {{ env_vars["CRONICLEKEY"] }}
    - name: Make Downloads directory
      become: true
      ansible.builtin.file:
        path: "{{ env_vars['DOWNLOADSDIR'] }}"
        state: directory
        mode: '0666'
    - name: Change Downloads Directory Owner to dan
      become: true
      ansible.builtin.file:
        path: "{{ env_vars['DOWNLOADSDIR'] }}"
        owner: "{{ user }}"
        group: "{{ group }}"
    - name: Run Docker Compose Up
      community.docker.docker_compose_v2:
        project_src: "{{ main }}/docker/mediastack"
        state: present
      register: output
    - name: Show Results
      ansible.builtin.debug:
        var: output