---
- name: Playbook to download private secrets from github
  become: true
  hosts: localhost
  connection: local
  vars:
    username: leinad13
    reponame: homeserversecrets
    dest: ~/homeserversecrets
  tasks:
    - name: Clone Private Git Repo
      ansible.builtin.git:
        repo: "https://{{ token }}@github.com/{{ username }}/{{ reponame }}.git"
        dest: "~/"
        