---
- name: Playbook to download and install mergerfs
  become: true
  hosts: localhost
  connection: local
  tasks:
    - name: Download mergerfs
      ansible.builtin.get_url:
        url: https://github.com/trapexit/mergerfs/releases/download/2.40.2/mergerfs_2.40.2.ubuntu-noble_amd64.deb
        dest: /tmp/mergerfs_2.40.2.ubuntu-noble_amd64.deb
    - name: Install mergerfs
      ansible.builtin.apt:
        deb: /tmp/mergerfs_2.40.2.ubuntu-noble_amd64.deb
      become: true